// Generated by tools/mkfont.py from tools/fonts/VT323-Regular.ttf @ 22px. Do not edit.
#ifndef _ui_fonts_g_font_vt323_22_h
#define _ui_fonts_g_font_vt323_22_h
#include "../font.h"
extern const Font g_font_vt323_22;
#endif
