// Generated by tools/mkfont.py from tools/fonts/PressStart2P-Regular.ttf @ 8px. Do not edit.
#ifndef _ui_fonts_g_font_ps2p8_h
#define _ui_fonts_g_font_ps2p8_h
#include "../font.h"
extern const Font g_font_ps2p8;
#endif
