//
// src/video/splash_data.h
//
// Bare Metal Sega Genesis
// Embedded boot-splash logo (generated by tools/mksplash.py — do not edit the
// generated splash_data.cpp by hand). RGB565, g_splash_w * g_splash_h pixels.
//

#ifndef _video_splash_data_h
#define _video_splash_data_h

extern const unsigned       g_splash_w;
extern const unsigned       g_splash_h;
extern const unsigned short g_splash_data[];

#endif
