#!/usr/bin/env python3
"""Render a TTF into a Bare-Metal-Genesis bitmap Font (src/ui/font.h format).

Usage: mkfont.py <ttf> <px_size> <symbol> <out_basename_no_ext>
  e.g. mkfont.py tools/fonts/PressStart2P-Regular.ttf 8 g_font_ps2p8 src/ui/fonts/font_ps2p8
Emits <out>.h and <out>.cpp. Covers ASCII 0x20..0x7E, fixed-width cells.
Requires Pillow (pip install pillow).
"""
import sys
from PIL import Image, ImageFont, ImageDraw

FIRST, LAST = 0x20, 0x7E

def main():
    ttf, px, symbol, out = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
    font = ImageFont.truetype(ttf, px)

    # Fixed cell: max advance width over the range, and the px size as height.
    width = 0
    for cp in range(FIRST, LAST + 1):
        box = font.getbbox(chr(cp))
        adv = box[2] - box[0] if box else 0
        width = max(width, adv)
    width = max(width, 1)
    height = px
    stride = (width + 7) // 8

    rows = []
    for cp in range(FIRST, LAST + 1):
        img = Image.new("L", (width, height), 0)
        d = ImageDraw.Draw(img)
        # Draw at a fixed origin so every glyph shares the same baseline (PIL's
        # default "la" anchor references the ascender line). Per-glyph bbox
        # shifting would break baseline alignment (descenders float upward).
        d.text((0, 0), chr(cp), fill=255, font=font)
        px_on = img.load()
        for gy in range(height):
            for byte_i in range(stride):
                b = 0
                for bit in range(8):
                    gx = byte_i * 8 + bit
                    on = gx < width and px_on[gx, gy] >= 128
                    if on:
                        b |= 1 << (7 - bit)
                rows.append(b)

    base = symbol
    header_guard = "_ui_fonts_%s_h" % symbol
    with open(out + ".h", "w") as f:
        f.write("// Generated by tools/mkfont.py from %s @ %dpx. Do not edit.\n" % (ttf, px))
        f.write("#ifndef %s\n#define %s\n#include \"../font.h\"\n" % (header_guard, header_guard))
        f.write("extern const Font %s;\n#endif\n" % base)
    with open(out + ".cpp", "w") as f:
        f.write("// Generated by tools/mkfont.py from %s @ %dpx. Do not edit.\n" % (ttf, px))
        f.write("#include \"%s.h\"\n" % out.split("/")[-1])
        f.write("static const uint8_t kBits[] = {\n")
        for i in range(0, len(rows), 12):
            f.write("  " + ",".join("0x%02X" % b for b in rows[i:i+12]) + ",\n")
        f.write("};\n")
        f.write("const Font %s = { 0x%02X, 0x%02X, %d, %d, %d, kBits };\n"
                % (base, FIRST, LAST, width, height, stride))
    print("wrote %s.h / %s.cpp  (%dx%d, stride %d)" % (out, out, width, height, stride))

if __name__ == "__main__":
    main()
