#!/usr/bin/env python3
"""Convert a PNG (or a procedural placeholder) to the boot-splash asset.

Usage:
  mksplash.py --placeholder --cpp src/video/splash_data.cpp
  mksplash.py logo.png      --cpp src/video/splash_data.cpp
  mksplash.py --placeholder --raw splash.raw
  mksplash.py logo.png      --raw splash.raw

PNG input requires Pillow; --placeholder needs nothing but the stdlib.
"""
import sys
import struct
import argparse


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def placeholder(w=160, h=100):
    """Dark field with three colored vertical bars (red/blue/yellow)."""
    bg = (24, 24, 32)
    bars = [(220, 40, 40), (40, 90, 220), (230, 200, 40)]
    bar_w, gap = 24, 12
    total = len(bars) * bar_w + (len(bars) - 1) * gap
    x0 = (w - total) // 2
    y0, y1 = h * 20 // 100, h * 80 // 100
    px = []
    for y in range(h):
        for x in range(w):
            c = bg
            if y0 <= y < y1:
                rel = x - x0
                if 0 <= rel < total:
                    slot = rel // (bar_w + gap)
                    off = rel - slot * (bar_w + gap)
                    if slot < len(bars) and off < bar_w:
                        c = bars[slot]
            px.append(rgb565(*c))
    return w, h, px


def from_png(path):
    from PIL import Image
    im = Image.open(path).convert("RGB")
    w, h = im.size
    px = [rgb565(r, g, b) for (r, g, b) in im.getdata()]
    return w, h, px


def write_cpp(path, w, h, px):
    with open(path, "w") as f:
        f.write("//\n// src/video/splash_data.cpp\n//\n")
        f.write("// Generated by tools/mksplash.py - do not edit.\n//\n\n")
        f.write('#include "splash_data.h"\n\n')
        f.write("const unsigned       g_splash_w = %d;\n" % w)
        f.write("const unsigned       g_splash_h = %d;\n" % h)
        f.write("const unsigned short g_splash_data[%d] = {\n" % (w * h))
        for i in range(0, len(px), 12):
            row = ",".join("0x%04x" % v for v in px[i:i + 12])
            f.write("    " + row + ",\n")
        f.write("};\n")


def write_raw(path, w, h, px):
    with open(path, "wb") as f:
        f.write(b"SGSP")
        f.write(struct.pack("<HH", w, h))
        for v in px:
            f.write(struct.pack("<H", v))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("png", nargs="?")
    ap.add_argument("--placeholder", action="store_true")
    ap.add_argument("--cpp")
    ap.add_argument("--raw")
    a = ap.parse_args()
    if a.placeholder:
        w, h, px = placeholder()
    elif a.png:
        w, h, px = from_png(a.png)
    else:
        ap.error("give a PNG or --placeholder")
    if not a.cpp and not a.raw:
        ap.error("give --cpp and/or --raw")
    if a.cpp:
        write_cpp(a.cpp, w, h, px)
    if a.raw:
        write_raw(a.raw, w, h, px)
    print("splash %dx%d -> %s" % (w, h, a.cpp or a.raw))


if __name__ == "__main__":
    main()
